### ISSUE TITLE
Assigning nominal codes to invoice/credit lines

### ISSUE THREAD

**Issue by pdashford** [darroncockram/sdatasamples#3]
Hi, could someone point me in the direction of how you assign an invoice/credit line to a nominal code using the Sdata XML. Is there information somewhere as to what fields are available in the Sdata posts? Thanks

**Comment by darroncockram** [comment]
> Hi, could someone point me in the direction of how you assign an invoice/credit line to a nominal code using the Sdata XML.

I've not checked if it is supported for invoices/credits but assuming it is then you'd set the financialAccounts property similar to this example for sales orders: https://github.com/darroncockram/sdatasamples/blob/master/CreateSalesOrder/Program.cs

> Is there information somewhere as to what fields are available in the Sdata posts?

Sdata is considered to be self documenting via the schema endpoint https://sage.github.io/SData-2.0/pages/core/0207/ as each provider may support different properties and feeds within a given contract.

Hope that helps.

**Comment by pdashford** [comment]
Thanks @darroncockram I'll give that a go!

**Comment by pdashford** [comment]
So if I'm using the xml would it be 

<financialAccounts>
 <financialAccount sdata:uuid="nominal guid"></financialAccount>
</financialAccounts>

Also I am trying to post the line item as an S1 code but not sure how you setup the type. Would be really good to have a full xml post.

This is what I have so far, I get an entry, but it does not show as an S1 line and not allocations;

`<?xml version="1.0" encoding="UTF-8"?>
<entry xmlns="http://www.w3.org/2005/Atom" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:cf="http://www.microsoft.com/schemas/rss/core/2005" xmlns:http="http://schemas.sage.com/sdata/http/2008/1" xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/" xmlns:sdata="http://schemas.sage.com/sdata/2008/1" xmlns:sdatasync="http://schemas.sage.com/sdata/sync/2008/1" xmlns:sme="http://schemas.sage.com/sdata/sme/2007" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <sdata:payload>
      <salesInvoice xmlns="http://schemas.sage.com/crmErp/2008">
         <reference>customer order</reference>
         <reference2>order number</reference2>
         <type>Product Invoice</type>
         <customerReference>customer reference</customerReference>
         <taxDate>2020-09-01T22:59:59.000Z</taxDate>
         <tradingAccount sdata:uuid="dc2e08b4-637e-4361-9cb0-23f39983699c" />
         <salesInvoiceLines>
            <salesInvoiceLine>
               <type>0</type>
               <taxCodes>
                  <taxCode sdata:uuid="03c41c3d-9a7a-4425-8cc5-64bf4f23bc94" />
               </taxCodes>
               <text>some text</text>
               <quantity>1</quantity>
               <actualPrice>100</actualPrice>
               <netTotal>100</netTotal>
               <notes>notes</notes>
               <financialAccounts>
                  <financialAccount sdata:uuid="6bad6401-3620-4c9d-b196-fcb685eeb87c" />
               </financialAccounts>
            </salesInvoiceLine>
         </salesInvoiceLines>
         <netTotal>100</netTotal>
         <taxTotal>20</taxTotal>
         <text1>text1</text1>
         <text2>text2</text2>
         <notes>notes</notes>
         <user>user</user>
      </salesInvoice>
   </sdata:payload>
</entry>`

Thanks so far for your help @darroncockram

**Comment by pdashford** [comment]
Managed to get the S1 line by using type `Free Text` just the financial account allocation now

**Comment by darroncockram** [comment]
> Would be really good to have a full xml post.

Best bet for that would be to run one of the samples and capture the request response using a tool such as Fiddler

**Comment by pdashford** [comment]
Thanks @darroncockram got the sample code up and running but Fiddler is only showing the GET requests and not the POST request
